[project]
name = "pacmann_cashier"
version = "0.1"
dependencies = ["pandas", "pyfiglet", "tabulate"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
cashier = "app.main:main"